services:
  digester:
    build: "./digester"
    environment:
      - TUMMY_USERNAME=${TUMMY_USERNAME}
      - TUMMY_PASSWORD=${TUMMY_PASSWORD}
      - TUMMY_DB=tummy
      - TUMMY_PORT=${TUMMY_PORT}
      - TUMMY_HOST=tummy
    volumes:
      - ${ZIPFILE_PATH}:/slack-export.zip
    networks:
      digestive-tract:
        aliases:
          - mouth

networks:
  digestive-tract:
    name: digestive-tract
    external: true
