services:
  tummy:
    image: postgres
    profiles: ["digest", "excrete"]
    restart: always
    environment:
      - POSTGRES_USER=${TUMMY_USERNAME}
      - POSTGRES_PASSWORD=${TUMMY_PASSWORD}
      - POSTGRES_DB=tummy
      - PGPORT=${TUMMY_PORT}
      - PGHOST=tummy
    volumes:
      - ./tummy/init.sql:/docker-entrypoint-initdb.d/init.sql
      - food:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      timeout: 3s
      retries: 20
    networks:
      digestive-tract:
        aliases:
          - tummy

  excretor:
    build: "./excretor"
    profiles: ["excrete"]
    restart: always
    depends_on:
      tummy:
        condition: service_healthy
    environment:
      - TUMMY_USERNAME=${TUMMY_USERNAME}
      - TUMMY_PASSWORD=${TUMMY_PASSWORD}
      - TUMMY_DB=tummy
      - TUMMY_PORT=${TUMMY_PORT}
      - TUMMY_HOST=tummy
    networks:
      digestive-tract:
        aliases:
          - excretor

  digester:
    build: "./digester"
    profiles: ["digest"]
    depends_on:
      tummy:
        condition: service_healthy
    environment:
      - TUMMY_USERNAME=${TUMMY_USERNAME}
      - TUMMY_PASSWORD=${TUMMY_PASSWORD}
      - TUMMY_DB=tummy
      - TUMMY_PORT=${TUMMY_PORT}
      - TUMMY_HOST=tummy
    volumes:
      - ${ZIPFILE_PATH}:/slack-export.zip
    networks:
      digestive-tract:
        aliases:
          - mouth

networks:
  digestive-tract:
    name: digestive-tract

volumes:
  food:
